// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: sleep/sleep.proto

package sleep

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GoSleepClient is the client API for GoSleep service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoSleepClient interface {
	Sleep(ctx context.Context, in *SleepRequest, opts ...grpc.CallOption) (*SleepReply, error)
}

type goSleepClient struct {
	cc grpc.ClientConnInterface
}

func NewGoSleepClient(cc grpc.ClientConnInterface) GoSleepClient {
	return &goSleepClient{cc}
}

func (c *goSleepClient) Sleep(ctx context.Context, in *SleepRequest, opts ...grpc.CallOption) (*SleepReply, error) {
	out := new(SleepReply)
	err := c.cc.Invoke(ctx, "/sleep.GoSleep/Sleep", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoSleepServer is the server API for GoSleep service.
// All implementations must embed UnimplementedGoSleepServer
// for forward compatibility
type GoSleepServer interface {
	Sleep(context.Context, *SleepRequest) (*SleepReply, error)
	mustEmbedUnimplementedGoSleepServer()
}

// UnimplementedGoSleepServer must be embedded to have forward compatible implementations.
type UnimplementedGoSleepServer struct {
}

func (UnimplementedGoSleepServer) Sleep(context.Context, *SleepRequest) (*SleepReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sleep not implemented")
}
func (UnimplementedGoSleepServer) mustEmbedUnimplementedGoSleepServer() {}

// UnsafeGoSleepServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoSleepServer will
// result in compilation errors.
type UnsafeGoSleepServer interface {
	mustEmbedUnimplementedGoSleepServer()
}

func RegisterGoSleepServer(s grpc.ServiceRegistrar, srv GoSleepServer) {
	s.RegisterService(&GoSleep_ServiceDesc, srv)
}

func _GoSleep_Sleep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SleepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoSleepServer).Sleep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sleep.GoSleep/Sleep",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoSleepServer).Sleep(ctx, req.(*SleepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoSleep_ServiceDesc is the grpc.ServiceDesc for GoSleep service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoSleep_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sleep.GoSleep",
	HandlerType: (*GoSleepServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sleep",
			Handler:    _GoSleep_Sleep_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sleep/sleep.proto",
}
