# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sleep.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bsleep.proto\x12\x05sleep\"8\n\x0cSleepRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\r\n\x05sleep\x18\x03 \x01(\x03\"I\n\nSleepReply\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\r\n\x05sleep\x18\x03 \x01(\x03\x12\x11\n\ttimestamp\x18\x04 \x01(\t2<\n\x07GoSleep\x12\x31\n\x05Sleep\x12\x13.sleep.SleepRequest\x1a\x11.sleep.SleepReply\"\x00\x42\"Z github.com/mmatww/go-sleep/sleepb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sleep_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z github.com/mmatww/go-sleep/sleep'
  _SLEEPREQUEST._serialized_start=22
  _SLEEPREQUEST._serialized_end=78
  _SLEEPREPLY._serialized_start=80
  _SLEEPREPLY._serialized_end=153
  _GOSLEEP._serialized_start=155
  _GOSLEEP._serialized_end=215
# @@protoc_insertion_point(module_scope)
